FinancesAlertsJob:
    Db:
        LogsConnString:
            settings-key: FinancesAlertsJob-LogsConnString
            types:
            - AzureTableStorage
        DataConnString:
            settings-key: FinancesAlertsJob-DataConnString
            types:
            - AzureTableStorage
        SqlConnString:
            settings-key: FinancesAlertsJob-SqlConnString
    CryptoFacilities:
        ApiPath:
            settings-key: FinancesAlertsJob-CfApiPath
        ApiPrivateKey:
            settings-key: FinancesAlertsJob-CfApiPrivateKey
        ApiPublicKey:
            settings-key: FinancesAlertsJob-CfApiPublicKey
    UseSmsMocks:
        settings-key: FinancesAlertsJob-UseSmsMocks
        types:
            - Optional
SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName:
            settings-key: SlackQueueName
MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl
SmsSenderServiceClient:
    ServiceUrl :
        settings-key: SmsSenderServiceUrl
EmailPartnerRouterServiceClient:
    ServiceUrl:
        settings-key: EmailPartnerRouterServiceUrl
